In [2]:
import pandas as pd
import numpy as np

In [3]:
wine = pd.read_csv("../../data/interm/wine_cleaned.csv")
wine

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test = train_test_split(
    wine,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
import joblib

joblib.dump(scaler, "../model developement/scaler.pkl")

['../model developement/scaler.pkl']

In [16]:
pd.DataFrame(X_train_scaled, columns=X_train.columns)

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,1.665293,-0.608406,1.218962,1.605400,-0.167384,0.804002,-0.691678,1.267226,1.877540,3.419473,-1.656329,-0.879409,-0.248606
1,-0.549525,2.751541,1.003315,1.605400,-0.304379,-0.785384,-1.401233,2.049600,-0.873505,-0.024801,-0.584633,-1.254621,-0.729922
2,-0.745310,-1.143541,-0.937507,-0.282704,-0.852357,1.937029,1.746791,-1.001659,0.587987,-0.240068,0.358460,0.246227,-0.248606
3,0.612948,-0.617179,1.003315,0.879206,-0.783860,0.489272,-0.901547,1.188988,1.172585,2.881305,-1.656329,-1.129550,-0.381383
4,0.111249,-0.766315,-0.937507,-1.154137,-0.167384,0.174542,0.637487,-0.688710,-0.409266,-0.584496,0.958609,0.135053,0.946386
...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1.077938,-0.757542,1.111138,1.605400,-0.989352,1.040049,0.857349,-1.236371,0.450435,-0.722267,1.730230,0.788199,-1.078462
138,-0.892149,-0.564542,-0.865625,-0.137465,-1.400336,-1.005695,0.027870,0.015427,0.037778,-0.713656,0.186988,0.802096,-0.746519
139,1.714239,-0.441724,0.068845,-2.170809,0.106605,1.590826,1.636860,-0.610472,2.324585,1.051535,1.044345,0.565852,2.695722
140,-0.353740,-0.739996,-0.362449,0.356346,-1.400336,-1.430580,-0.541773,1.658413,0.020584,-0.864343,0.015517,-0.740442,-0.796311
141,-0.782020,0.067093,0.356374,0.443490,-0.167384,0.426326,0.107820,-0.219285,-0.512431,-0.971977,-0.670368,1.093928,-0.985518