In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import (
    silhouette_score
)

In [3]:
wine = pd.read_csv("../../Data/interim/wine_cleaned.csv")
wine.head()

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [4]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(wine)
print(wine.shape)
print(X_scaled.shape)

(178, 13)
(178, 13)

In [5]:
# Train K-Means
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

kmeans_labels = kmeans.fit_predict(X_scaled)

# Train Hierarchical Clustering
hierarchical = AgglomerativeClustering(
    n_clusters=3,
    linkage="ward"
)

hierarchical_labels = hierarchical.fit_predict(X_scaled)

print("Both models trained successfully.")

Both models trained successfully.

c:\Users\veere\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1428: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [7]:
comparison = pd.DataFrame([
    {
        "Model": "K-Means",
        "Silhouette Score": silhouette_score(X_scaled, kmeans_labels)
    },
    {
        "Model": "Hierarchical Clustering",
        "Silhouette Score": silhouette_score(X_scaled, hierarchical_labels)
    }
])

display(comparison.round(4))

                     Model  Silhouette Score
0                  K-Means            0.2849
1  Hierarchical Clustering            0.2774